# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'parent' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for parent
  pod 'PRTween'

  target 'parentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'parentUITests' do
    # Pods for testing
  end

end
